steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}-dev:$BUILD_ID', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}-dev:$BUILD_ID']
    
  # Deploy to Cloud Run (dev environment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}-dev:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=development'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,OPENWEATHER_API_KEY=openweather-api-key:latest'
      - '--tag'
      - 'dev'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}-dev:$BUILD_ID'

# Substitution variables
substitutions:
  _SERVICE_NAME: 'weather-agent'
  _REGION: 'us-central1'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_2' 